name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - 'feat/*'


jobs:
  universum_check:
    name: Universum check
    runs-on: ubuntu-latest

    steps:
    - name: Setup python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependency
      run: |
        pip install universum
        pip install gitpython
        

    - name: Install ClangFormat
      run: |
        sudo apt-get install clang-format
        sudo apt-get install git

    - name: Universum
      run:
        python -u -m universum
        --vcs-type="ghactions"
        --ghactions-payload="@${{ github.event_path }}"
        --ghactions-token="${{ secrets.GITHUB_TOKEN }}"
        --report-to-review
        --out-type github
        --report-build-start
        --no-diff
        --fail-unsuccessful

    - name: Collect artifacts
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: artifacts
        path: artifacts
